name: Transactions Bot

on:
  schedule:
    - cron: "0 13,16,19,22 * * *"
    # PDT:     6 ,9 ,12,15
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download sent-transactions artifact
      uses: actions/download-artifact@v4
      with:
        name: sent-transactions
        path: .
      continue-on-error: true

    - name: Run transactions script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python transactions.py

    - name: Upload sent-transactions artifact
      uses: actions/upload-artifact@v4
      with:
        name: sent-transactions
        path: sent-transactions.json
        overwrite: true
